runMode: release
logfile: ../logs/gin.log
metricfile: ../logs/metric.prom
addr: :8080
timeout: 1s500ms

jwt:
  jwtissuer: ginfra
  jwtexpires: 604800 # 7 * 24 * 3600
  RS256KeyDir: ../jwt/
  domain: .qq.com
  headername: token
  cookiename: token

cors:
  origins:
  - https://www.qq.com/

wx:
  SignatureToken: xxxx

tcb:
  secretId: xxxx
  secretKey: xxxx

cos:
  BucketURL: https://xxxx.cos.ap-shanghai.myqcloud.com
  SecretID: xxxx
  SecretKey: xxxx

qcloud:
  SecretID: xxxx
  SecretKey: xxxx
            
db:         
  dialect: mysql # sqlite3
  url: root:ginfra%007@tcp(127.0.0.1:33060)/test?charset=utf8&parseTime=True&loc=Local&timeout=10s&readTimeout=30s&writeTimeout=60s # /tmp/gorm.db
  maxopenconns: 100
  maxidleconns: 10
  logmode: true
